export const en = {
  "Usuário encontrado": "User found:",
    "Login realizado com sucesso!": "Login successful!",
    "Erro": "Error",
  "Email ou senha inválidos. Por favor, tente novamente.": "Email or password invalid. Please try again.",
  'Login': 'Login',
  'hello': 'hello',
  'pt_br': 'Brazilian Portuguese',
  'es': 'Spanish',
  'en': 'English',
  'open_menu': 'Open Menu',
  'home': 'Home',
  "Carrinho": "Cart",
  'languages': 'Languages',
  'Cardapio': 'Menu',
  'Cadastro': 'Register',
  'Perfis': 'Profiles',
  'Perfil': 'Profile',
  'Historico': 'History',
  'Dashboard': 'Dashboard',
  'Dicionario': 'Dictionary',
  'Vendas de cada mes': 'Sales by month',
  'Vendas por dia': 'Sales by day',
  'Total de vendas': 'Total sales',
  'Total de produtos vendidos': 'Total products sold',
  'Novos usuários por dia': 'New users by day',
  'Usuários que fizeram compras': 'Users who purchased',
  'Número do Pedido:': 'Order Number:',
  'Data:': 'Date:',
  'Status:': 'Status:',
  'Total:': 'Total:',
  'Itens': 'Items',
  'Quantidade:': 'Quantity:',
  'Preço:': 'Price:',
  'Histórico de compras': 'Purchase History',
  'Jan': 'Jan',
  'Feb': 'Feb',
  'Mar': 'Mar',
  'Apr': 'Apr',
  'May': 'May',
  'Jun': 'Jun',
  'Jul': 'Jul',
  'Aug': 'Aug',
  'Sep': 'Sep',
  'Oct': 'Oct',
  'Nov': 'Nov',
  'Deslogar': 'Logout',
  'Dec': 'Dec',
  'Total Atual:': 'Current Total:',
  'Fechar': 'Close',
  'Não compraram': 'Did not purchase',
  'Compraram': 'Purchased',
  'Roupas': 'Clothes',
  'Acessórios': 'Accessories',
  'Calçados': 'Shoes',
  'Cerveja': 'Beer',
  'Vinho': 'Wine',
  'Destilado': 'Distilled',
  'Licor': 'Liquor',
  'Aguardando Pagamento': 'Awaiting Payment',
  'Cancelado': 'Canceled',
  'Em Preparação': 'In Preparation',
  'Entregue': 'Delivered',
  'Em trânsito': 'In Transit',
   'Descrição:': 'Description:',
  'COMPRAR': 'BUY',
  'Selecione um filtro...': 'Select a filter...',
  'Filtro de pesquisa:': 'Search filter:',
  'Cerveja lager leve, refrescante e saborosa, uma das mais populares no mercado.': 'Light, refreshing, and tasty lager beer, one of the most popular on the market.',
  'Cerveja pilsen leve, com sabor suave e refrescante, muito apreciada pelos consumidores.': 'Light pilsen beer with a mild and refreshing taste, highly appreciated by consumers.',
  'Cerveja premium de origem holandesa, com sabor marcante e amargor equilibrado.': 'Premium Dutch beer with a strong flavor and balanced bitterness.',
  'Vinho fresco e leve, ideal para acompanhar frutos do mar e pratos leves.': 'Fresh and light wine, ideal to pair with seafood and light dishes.',
  'Vinho encorpado, com sabores ricos de frutas vermelhas e taninos equilibrados.': 'Full-bodied wine with rich flavors of red fruits and balanced tannins.',
  'Bebida espumante e festiva, com sabor refrescante e notas frutadas.': 'Sparkling and festive drink with refreshing flavor and fruity notes.',
  'Destilado neutro, popular em coquetéis, com sabor limpo e suave.': 'Neutral distilled beverage, popular in cocktails, with a clean and smooth flavor.',
  'Destilado de malte ou grãos, com sabor amadeirado e notas de caramelo.': 'Malt or grain distilled beverage, with woody flavor and caramel notes.',
  'Destilado de agave mexicano, com sabor terroso e toques de pimenta.': 'Mexican agave distilled beverage, with earthy flavor and peppery touches.',
  'Destilado brasileiro de cana-de-açúcar, usado para preparar caipirinhas.': 'Brazilian sugarcane distilled beverage, used to make caipirinhas.',
  'Licor italiano com sabor de amêndoas, ideal para sobremesas e coquetéis.': 'Italian liqueur with almond flavor, ideal for desserts and cocktails.',
  'Licor cremoso de origem irlandesa, com sabor de café e chocolate.': 'Creamy Irish liqueur with coffee and chocolate flavor.',
  'Licor francês de laranja, com notas ricas e complexas.': 'French orange liqueur with rich and complex notes.',
  'Nenhum perfil encontrado.': 'No profile found.',
  'Detalhes do Perfil': 'Profile Details',
  'Email:': 'Email:',
  'CEP:': 'ZIP Code:',
  'Endereço:': 'Address:',
  'Cidade:': 'City:',
  'Estado:': 'State:',
  'País:': 'Country:',
  'Não informado': 'Not provided',
  'Editar Perfil': 'Edit Profile',
  'Nenhum perfil salvo.': 'No saved profile.',
  'Nome do Usuário': 'User Name',
  'Detalhes Pessoais': 'Personal Details',
  'Id:': 'Id:',
  'Endereço Comercial': 'Business Address',
  'Conta Bancária': 'Bank Account',
  'Número da Conta:': 'Account Number:',
  'Validade:': 'Validity:',
  'Salvar': 'Save',
  'Selecione um país': 'Select a country',
  'Nome completo': 'Full name',
  'Endereço de Email': 'Email address',
  'Senha': 'Password',
  'Detalhes do Endereço Comercial': 'Business Address Details',
  'CEP': 'ZIP Code',
  'Endereço': 'Address',
  'Cidade': 'City',
  'Estado': 'State',
  'País': 'Country',
  'Número da Conta Bancária': 'Bank Account Number',
  'Nome do Titular da Conta': 'Account Holder Name',
  'Validade': 'Validity',
  'Cvv': 'Cvv',
  'Brasil': 'Brazil',
  'Estados Unidos': 'United States',
  'Canadá': 'Canada',
  'Reino Unido': 'United Kingdom',
  'Voltar': 'Back',
  'ADICIONAR AO CARRINHO': 'ADD TO CART',
  'Imagem': 'Image',
  'Bem-vindo!': 'Welcome!',
  'Digite seu email': 'Enter your email',
  'Digite sua senha': 'Enter your password',
  'Entrar': 'Login',
  'Cadastrar-se': 'Sign Up',
  'Login bem-sucedido!': 'Login successful!',
  'Usuário ou senha incorretos!': 'Incorrect username or password!',
  "Carrinho de Compras": "Shopping Cart",
  "Quantidade": "Quantity",
  "Preço": "Price",
  "Remover": "Remove",
  "Carrinho vazio": "Cart is empty",
  "Total": "Total",
  "Finalizar Compra": "Checkout",
  'X':'X',
  "Checkout": "Checkout",
  "Usuário": "User",
  "Usuário não logado": "User not logged in",
  "Realizar Pedido": "Place Order",
  "Número do Pedido": "Order Number",
  "Data": "Date",
  "Status": "Status",
  'Pagamento': 'Payment',
  'Pix': 'Pix',
  'Cartão': 'Card',
  'Boleto': 'Invoice',
  'Continuar': 'Continue',
  'Por favor, selecione um método de pagamento': 'Please select a payment method',
  'Pagar':'Pay'
};

export const pt_br = {
  "Usuário encontrado:": "Usuário encontrado:",
  "Login realizado com sucesso!": "Login realizado com sucesso!",
  "Erro": "Erro",
  'Email ou senha inválidos. Por favor, tente novamente.': 'Email ou senha inválidos. Por favor, tente        novamente.',
  'Login': 'Login',
  'Deslogar': 'Deslogar',
  'Bem-vindo!': 'Bem-vindo!',
  'Digite seu email': 'Digite seu email',
  'Digite sua senha': 'Digite sua senha',
  'Entrar': 'Entrar',
  'Cadastrar-se': 'Cadastrar-se',
  'Login bem-sucedido!': 'Login bem-sucedido!',
  'Usuário ou senha incorretos!': 'Usuário ou senha incorretos!',
  'hello': 'oi',
  'pt_br': 'Português do Brasil',
  'es': 'Espanhol',
  'en': 'Inglês',
  'open_menu': 'Abrir Menu',
  'home': 'Início',
  'languages': 'Línguas',
  'Cardapio': 'Cardápio',
  'Cadastro': 'Cadastro',
  'Perfis': 'Perfis',
  'Perfil': 'Perfil',
  'Historico': 'Histórico',
  'Dashboard': 'Painel de Controle',
  'Dicionario': 'Dicionário',
  'Vendas de cada mes': 'Vendas de cada mês',
  'Vendas por dia': 'Vendas por dia',
  'Total de vendas': 'Total de vendas',
  'Total de produtos vendidos': 'Total de produtos vendidos',
  'Novos usuários por dia': 'Novos usuários por dia',
  'Usuários que fizeram compras': 'Usuários que fizeram compras',
  'Número do Pedido:': 'Número do Pedido:',
  'Data:': 'Data:',
  'Status:': 'Status:',
  'Total:': 'Total:',
  'Itens': 'Itens',
  'Quantidade:': 'Quantidade:',
  'Preço:': 'Preço:',
  'Histórico de compras': 'Histórico de compras',
  'Jan': 'Jan',
  'Feb': 'Fev',
  'Mar': 'Mar',
  'Apr': 'Abr',
  'May': 'Mai',
  'Jun': 'Jun',
  'Jul': 'Jul',
  'Aug': 'Ago',
  'Sep': 'Set',
  'Oct': 'Out',
  'Nov': 'Nov',
  'Dec': 'Dez',
  'Total Atual:': 'Total Atual:',
  'Fechar': 'Fechar',
  'Não compraram': 'Não compraram',
  'Compraram': 'Compraram',
  'Roupas': 'Roupas',
  'Acessórios': 'Acessórios',
  'Calçados': 'Calçados',
  'Cerveja': 'Cerveja',
  'Vinho': 'Vinho',
  'Destilado': 'Destilado',
  'Licor': 'Licor',
  'Aguardando Pagamento': 'Aguardando Pagamento',
  'Cancelado': 'Cancelado',
  'Em Preparação': 'Em Preparação',
  'Entregue': 'Entregue',
  'Em trânsito': 'Em trânsito',
  'Descrição:': 'Descrição:',
  'COMPRAR': 'COMPRAR',
  'Selecione um filtro...': 'Selecione um filtro...',
  'Filtro de pesquisa:': 'Filtro de pesquisa:',
  'Cerveja lager leve, refrescante e saborosa, uma das mais populares no mercado.': 'Cerveja lager leve, refrescante e saborosa, uma das mais populares no mercado.',
  'Cerveja pilsen leve, com sabor suave e refrescante, muito apreciada pelos consumidores.': 'Cerveja pilsen leve, com sabor suave e refrescante, muito apreciada pelos consumidores.',
  'Cerveja premium de origem holandesa, com sabor marcante e amargor equilibrado.': 'Cerveja premium de origem holandesa, com sabor marcante e amargor equilibrado.',
  'Vinho fresco e leve, ideal para acompanhar frutos do mar e pratos leves.': 'Vinho fresco e leve, ideal para acompanhar frutos do mar e pratos leves.',
  'Vinho encorpado, com sabores ricos de frutas vermelhas e taninos equilibrados.': 'Vinho encorpado, com sabores ricos de frutas vermelhas e taninos equilibrados.',
  'Bebida espumante e festiva, com sabor refrescante e notas frutadas.': 'Bebida espumante e festiva, com sabor refrescante e notas frutadas.',
  'Destilado neutro, popular em coquetéis, com sabor limpo e suave.': 'Destilado neutro, popular em coquetéis, com sabor limpo e suave.',
  'Destilado de malte ou grãos, com sabor amadeirado e notas de caramelo.': 'Destilado de malte ou grãos, com sabor amadeirado e notas de caramelo.',
  'Destilado de agave mexicano, com sabor terroso e toques de pimenta.': 'Destilado de agave mexicano, com sabor terroso e toques de pimenta.',
  'Destilado brasileiro de cana-de-açúcar, usado para preparar caipirinhas.': 'Destilado brasileiro de cana-de-açúcar, usado para preparar caipirinhas.',
  'Licor italiano com sabor de amêndoas, ideal para sobremesas e coquetéis.': 'Licor italiano com sabor de amêndoas, ideal para sobremesas e coquetéis.',
  'Licor cremoso de origem irlandesa, com sabor de café e chocolate.': 'Licor cremoso de origem irlandesa, com sabor de café e chocolate.',
  'Licor francês de laranja, com notas ricas e complexas.': 'Licor francês de laranja, com notas ricas e complexas.',
  'Nenhum perfil encontrado.': 'Nenhum perfil encontrado.',
  'Detalhes do Perfil': 'Detalhes do Perfil',
  'Email:': 'Email:',
  'CEP:': 'CEP:',
  'Endereço:': 'Endereço:',
  'Cidade:': 'Cidade:',
  'Estado:': 'Estado:',
  'País:': 'País:',
  'Não informado': 'Não informado',
  'Editar Perfil': 'Editar Perfil',
  'Nenhum perfil salvo.': 'Nenhum perfil salvo.',
  'Nome do Usuário': 'Nome do Usuário',
  'Detalhes Pessoais': 'Detalhes Pessoais',
  'Id:': 'Id:',
  'Endereço Comercial': 'Endereço Comercial',
  'Conta Bancária': 'Conta Bancária',
  'Número da Conta:': 'Número da Conta:',
  'Validade:': 'Validade:',
  'Salvar': 'Salvar',
  'Selecione um país': 'Selecione um país',
  'Nome completo': 'Nome completo',
  'Endereço de Email': 'Endereço de Email',
  'Senha': 'Senha',
  'Detalhes do Endereço Comercial': 'Detalhes do Endereço Comercial',
  'CEP': 'CEP',
  'Endereço': 'Endereço',
  'Cidade': 'Cidade',
  'Estado': 'Estado',
  'País': 'País',
  'Número da Conta Bancária': 'Número da Conta Bancária',
  'Nome do Titular da Conta': 'Nome do Titular da Conta',
  'Validade': 'Validade',
  'Cvv': 'Cvv',
  'Brasil': 'Brasil',
  'Estados Unidos': 'Estados Unidos',
  'Canadá': 'Canadá',
  'Reino Unido': 'Reino Unido',
  'Voltar': 'Voltar',
  'ADICIONAR AO CARRINHO': 'ADICIONAR AO CARRINHO',
  'Imagem': 'Imagem',
  "Carrinho": "Carrinho",
  "Carrinho de Compras": "Carrinho de Compras",
  "Quantidade": "Quantidade",
  "Preço": "Preço",
  "Remover": "Remover",
  "Carrinho vazio": "Carrinho vazio",
  "Total": "Total",
  "Finalizar Compra": "Finalizar Compra",
  'X':'X',
  "Checkout": "Checkout",
  "Usuário": "Usuário",
  "Usuário não logado": "Usuário não logado",
  "Realizar Pedido": "Realizar Pedido",
  "Número do Pedido": "Número do Pedido",
  "Data": "Data",
  "Status": "Status",
  "Método de pagamento": "Método de pagamento",
  "Boleto": "Boleto",
  "Cartão": "Cartão",
  "Pix": "Pix",
  "Concluir Pedido": "Concluir Pedido",
  "Por favor, selecione um método de pagamento": "Por favor, selecione um método de pagamento",
  'Pagar':'Pagar',
  'Pagamento':'Pagamento'
};

export const es = {
  "Carrinho": "Carrito",
  'Login': 'Login',
  'Deslogar': 'Cerrar sesión',
  'Bem-vindo!': '¡Bienvenido!',
  'Digite seu email': 'Introduce tu correo electrónico',
  'Digite sua senha': 'Introduce tu contraseña',
  'Entrar': 'Iniciar sesión',
  'Cadastrar-se': 'Registrarse',
  'Login bem-sucedido!': '¡Inicio de sesión exitoso!',
  'Usuário ou senha incorretos!': '¡Usuario o contraseña incorrectos!',
  'hello': 'hola',
  'pt_br': 'Portugués Brasileño',
  'es': 'Español',
  'en': 'Inglés',
  'open_menu': 'Menú abierto',
  'home': 'Inicio',
  'languages': 'Idiomas',
  'Cardapio': 'Menú',
  'Cadastro': 'Registro',
  'Perfis': 'Perfiles',
  'Perfil': 'Perfil',
  'Historico': 'Historial',
  'Dashboard': 'Panel de Control',
  'Dicionario': 'Diccionario',
  'Vendas de cada mes': 'Ventas por mes',
  'Vendas por dia': 'Ventas por día',
  'Total de vendas': 'Ventas totales',
  'Total de produtos vendidos': 'Total de productos vendidos',
  'Novos usuários por dia': 'Nuevos usuarios por día',
  'Usuários que fizeram compras': 'Usuarios que compraron',
  'Número do Pedido:': 'Número de Pedido:',
  'Data:': 'Fecha:',
  'X':'X',
  'Status:': 'Estado:',
  'Total:': 'Total:',
  'Itens': 'Artículos',
  'Quantidade:': 'Cantidad:',
  'Preço:': 'Precio:',
  'Histórico de compras': 'Historial de compras',
  'Jan': 'Ene',
  'Feb': 'Feb',
  'Mar': 'Mar',
  'Apr': 'Abr',
  'May': 'May',
  'Jun': 'Jun',
  'Jul': 'Jul',
  'Aug': 'Ago',
  'Sep': 'Sep',
  'Oct': 'Oct',
  'Nov': 'Nov',
  'Dec': 'Dic',
  'Total Atual:': 'Total Actual:',
  'Fechar': 'Cerrar',
  'Não compraram': 'No compraron',
  'Compraram': 'Compraron',
  'Roupas': 'Ropa',
  'Acessórios': 'Accesorios',
  'Calçados': 'Zapatos',
  'Cerveja': 'Cerveza',
  'Vinho': 'Vino',
  'Destilado': 'Destilado',
  'Licor': 'Licor',
  'Aguardando Pagamento': 'Pendiente de Pago',
  'Cancelado': 'Cancelado',
  'Em Preparação': 'En Preparación',
  'Entregue': 'Entregado',
  'Em trânsito': 'En tránsito',
   'Descrição:': 'Descripción:',
  'COMPRAR': 'COMPRAR',
  'Selecione um filtro...': 'Seleccione un filtro...',
  'Filtro de pesquisa:': 'Filtro de búsqueda:',
  'Cerveja lager leve, refrescante e saborosa, uma das mais populares no mercado.': 'Cerveza lager ligera, refrescante y sabrosa, una de las más populares del mercado.',
  'Cerveja pilsen leve, com sabor suave e refrescante, muito apreciada pelos consumidores.': 'Cerveza pilsen ligera, con sabor suave y refrescante, muy apreciada por los consumidores.',
  'Cerveja premium de origem holandesa, com sabor marcante e amargor equilibrado.': 'Cerveza premium de origen holandés, con sabor intenso y amargor equilibrado.',
  'Vinho fresco e leve, ideal para acompanhar frutos do mar e pratos leves.': 'Vino fresco y ligero, ideal para acompañar mariscos y platos ligeros.',
  'Vinho encorpado, com sabores ricos de frutas vermelhas e taninos equilibrados.': 'Vino con cuerpo, con sabores ricos de frutos rojos y taninos equilibrados.',
  'Bebida espumante e festiva, com sabor refrescante e notas frutadas.': 'Bebida espumante y festiva, con sabor refrescante y notas afrutadas.',
  'Destilado neutro, popular em coquetéis, com sabor limpo e suave.': 'Destilado neutro, popular en cócteles, con sabor limpio y suave.',
  'Destilado de malte ou grãos, com sabor amadeirado e notas de caramelo.': 'Destilado de malta o granos, con sabor amaderado y notas de caramelo.',
  'Destilado de agave mexicano, com sabor terroso e toques de pimenta.': 'Destilado de agave mexicano, con sabor terroso y toques de pimienta.',
  'Destilado brasileiro de cana-de-açúcar, usado para preparar caipirinhas.': 'Destilado brasileño de caña de azúcar, usado para preparar caipirinhas.',
  'Licor italiano com sabor de amêndoas, ideal para sobremesas e coquetéis.': 'Licor italiano con sabor a almendras, ideal para postres y cócteles.',
  'Licor cremoso de origem irlandesa, com sabor de café e chocolate.': 'Licor cremoso de origen irlandés, con sabor a café y chocolate.',
  'Licor francês de laranja, com notas ricas e complexas.': 'Licor francés de naranja, con notas ricas y complejas.',
   'Nenhum perfil encontrado.': 'No se encontró ningún perfil.',
  'Detalhes do Perfil': 'Detalles del Perfil',
  'Email:': 'Correo electrónico:',
  'CEP:': 'Código Postal:',
  'Endereço:': 'Dirección:',
  'Cidade:': 'Ciudad:',
  'Estado:': 'Estado:',
  'País:': 'País:',
  'Não informado': 'No proporcionado',
  'Editar Perfil': 'Editar Perfil',
  'Nenhum perfil salvo.': 'No hay perfil guardado.',
  'Nome do Usuário': 'Nombre de Usuario',
  'Detalhes Pessoais': 'Detalles Personales',
  'Id:': 'Id:',
  'Endereço Comercial': 'Dirección Comercial',
  'Conta Bancária': 'Cuenta Bancaria',
  'Número da Conta:': 'Número de Cuenta:',
  'Validade:': 'Validez:',
  'Salvar': 'Guardar',
  'Selecione um país': 'Seleccione un país',
  'Nome completo': 'Nombre completo',
  'Endereço de Email': 'Dirección de correo electrónico',
  'Senha': 'Contraseña',
  'Detalhes do Endereço Comercial': 'Detalles de la Dirección Comercial',
  'CEP': 'Código Postal',
  'Endereço': 'Dirección',
  'Cidade': 'Ciudad',
  'Estado': 'Estado',
  'País': 'País',
  'Número da Conta Bancária': 'Número de Cuenta Bancaria',
  'Nome do Titular da Conta': 'Nombre del Titular de la Cuenta',
  'Validade': 'Validez',
  'Cvv': 'Cvv',
  'Brasil': 'Brasil',
  'Estados Unidos': 'Estados Unidos',
  'Canadá': 'Canadá',
  'Reino Unido': 'Reino Unido',
  'Voltar': 'Volver',
  'ADICIONAR AO CARRINHO': 'AGREGAR AL CARRITO',
  'Imagem': 'Imagen',
  "Usuário encontrado": "Usuario encontrado:",
    "Login realizado com sucesso!": "Inicio de sesión realizado con éxito!",
    "Erro": "Error",
    "Email ou senha inválidos. Por favor, tente novamente.": "Correo o contraseña inválidos. Por favor, inténtelo de nuevo.",
    "Carrinho de Compras": "Carrito de Compras",
  "Quantidade": "Cantidad",
  "Preço": "Precio",
  "Remover": "Eliminar",
  "Carrinho vazio": "Carrito vacío",
  "Total": "Total",
  "Finalizar Compra": "Finalizar Compra",
  "Checkout": "Pagar",
  "Usuário": "Usuario",
  "Usuário não logado": "Usuario no registrado",
  "Realizar Pedido": "Realizar Pedido",
  "Número do Pedido": "Número de Pedido",
  "Data": "Fecha",
  "Status": "Estado",
  'Pagamento': 'Pago',
  'Pix': 'Pix',
  'Cartão': 'Tarjeta',
  'Boleto': 'Factura',
  'Continuar': 'Continuar',
  'Por favor, selecione um método de pagamento': 'Por favor, seleccione un método de pago',
  'Pagar':'Pagar'
};
